# Generated by Django 4.1.4 on 2023-01-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="object_id",
        ),
    ]
